### ISSUE TITLE
"This tag could not be resolved to an ActionScript class. It will be ignored." in library project without source-path

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-as3mxml#294]
Hi Josh,

I have a library project that defines 2 components. One is used inside the other in MXML but is not recognized by AS3&MXML, although compiler is ok since is compiling and working properly.

Both components are declared in namespace declaration and I have configured asconfig.json with "namespace" and "include-namespace" correctly.

AS3&MXLM extension reports a "This tag is unexpected. It will be ignored." for the component of the same library declared in some mxml of the same library. As a workaround I can use dot notation to go to the same package, but I would like to be able to use URI namespaces to reduce code verbosity

Since this compiles right but reports an error in VSCode I assume this is a bug in the extension

Thanks

**Comment by joshtynjala** [comment]
Attaching sample project from @carlosrovira 

[royale_sample_prjs.zip](https://github.com/BowlerHatLLC/vscode-as3mxml/files/2691729/royale_sample_prjs.zip)

**Comment by joshtynjala** [comment]
Terminal output when attempting to build makes it clear that this is a bug in the Royale compiler:

	> Executing task: C:\Program Files\Java\jdk1.8.0_191\bin\java.exe -jar c:\Users\josht\Development\as3mxml\vscode-as3mxml\distribution\target\vscode-as3mxml\vscode-as3mxml\bin\asconfigc.jar --sdk c:\Users\josht\Development\Royale\sdks\royale-js-dev\royale-asjs --debug=true --project c:\Users\josht\Desktop\royale_sample_prjs\royale\royalelibs\samplelib\asconfig.json <

	args:
	+royalelib=c:\Users\josht\Development\Royale\sdks\royale-js-dev\royale-asjs\frameworks
	--debug=true
	+configname=royale
	--targets=JSRoyale
	--include-sources+=src/main/royale
	--include-classes+=LibExampleClasses
	--include-namespaces+=library://ns.royale.org/example
	--namespace
	library://ns.royale.org/example
	src/main/resources/libexample-manifest.xml
	--source-map=true
	--output=target/LibProject.swc
	target:JSRoyale
	COMPCJSCRoyale
	Could not find source for class com.example.MyMXMLExtendedComp in namespace library://ns.royale.org/example.


	c:\Users\josht\Desktop\royale_sample_prjs\royale\royalelibs\samplelib\src\main\royale\com\example\MyMXMLExtendedComp.mxml Internal error in syntax tree request subsystem, when generating code for: c:\Users\josht\Desktop\royale_sample_prjs\royale\royalelibs\samplelib\src\main\royale\com\example\MyMXMLExtendedComp.mxml: java.lang.ArrayIndexOutOfBoundsException: 0
	        at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleSyntaxTreeRequest(MXMLCompilationUnit.java:89)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase.processSyntaxTreeRequest(CompilationUnitBase.java:838)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$100(CompilationUnitBase.java:108)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase$2$1.call(CompilationUnitBase.java:262)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase$2$1.call(CompilationUnitBase.java:258)
	        at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
	        at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
	        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	        at java.lang.Thread.run(Thread.java:748)



	c:\Users\josht\Desktop\royale_sample_prjs\royale\royalelibs\samplelib\src\main\royale\com\example\MyMXMLExtendedComp.mxml Internal error in file
	scope builder subsystem, when generating code for: c:\Users\josht\Desktop\royale_sample_prjs\royale\royalelibs\samplelib\src\main\royale\com\example\MyMXMLExtendedComp.mxml: java.lang.NullPointerException
	        at org.apache.royale.compiler.internal.definitions.DefinitionBase.toStorageName(DefinitionBase.java:282)
	        at org.apache.royale.compiler.internal.definitions.DefinitionBase.<init>(DefinitionBase.java:128)
	        at org.apache.royale.compiler.internal.definitions.ScopedDefinitionBase.<init>(ScopedDefinitionBase.java:34)
	        at org.apache.royale.compiler.internal.definitions.MemberedDefinition.<init>(MemberedDefinition.java:37)
	        at org.apache.royale.compiler.internal.definitions.TypeDefinitionBase.<init>(TypeDefinitionBase.java:59)
	        at org.apache.royale.compiler.internal.definitions.ClassDefinitionBase.<init>(ClassDefinitionBase.java:60)
	        at org.apache.royale.compiler.internal.definitions.ClassDefinition.<init>(ClassDefinition.java:207)
	        at org.apache.royale.compiler.internal.definitions.ClassDefinition.<init>(ClassDefinition.java:188)
	        at org.apache.royale.compiler.internal.parsing.mxml.MXMLScopeBuilder.processRootTag(MXMLScopeBuilder.java:199)
	        at org.apache.royale.compiler.internal.parsing.mxml.MXMLScopeBuilder.build(MXMLScopeBuilder.java:169)
	        at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleFileScopeRequest(MXMLCompilationUnit.java:171)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase.processFileScopeRequest(CompilationUnitBase.java:863)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$200(CompilationUnitBase.java:108)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:287)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:283)
	        at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
	        at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
	        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	        at java.lang.Thread.run(Thread.java:748)



	c:\Users\josht\Desktop\royale_sample_prjs\royale\royalelibs\samplelib\src\main\royale\com\example\MyMXMLExtendedComp.mxml Internal error in outgoing dependency subsystem, when generating code for: c:\Users\josht\Desktop\royale_sample_prjs\royale\royalelibs\samplelib\src\main\royale\com\example\MyMXMLExtendedComp.mxml: java.lang.NullPointerException
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase.startParsingImports(CompilationUnitBase.java:909)
	        at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleOutgoingDependenciesRequest(MXMLCompilationUnit.java:240)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase.processOutgoingDependenciesRequest(CompilationUnitBase.java:891)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$500(CompilationUnitBase.java:108)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase$6$1.call(CompilationUnitBase.java:387)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase$6$1.call(CompilationUnitBase.java:383)
	        at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
	        at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
	        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	        at java.lang.Thread.run(Thread.java:748)



	c:\Users\josht\Desktop\royale_sample_prjs\royale\royalelibs\samplelib\src\main\royale\com\example\MyMXMLExtendedComp2.mxml Internal error in syntax tree request subsystem, when generating code for: c:\Users\josht\Desktop\royale_sample_prjs\royale\royalelibs\samplelib\src\main\royale\com\example\MyMXMLExtendedComp2.mxml: java.lang.ArrayIndexOutOfBoundsException: 0
	        at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleSyntaxTreeRequest(MXMLCompilationUnit.java:89)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase.processSyntaxTreeRequest(CompilationUnitBase.java:838)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$100(CompilationUnitBase.java:108)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase$2$1.call(CompilationUnitBase.java:262)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase$2$1.call(CompilationUnitBase.java:258)
	        at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
	        at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
	        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	        at java.lang.Thread.run(Thread.java:748)



	c:\Users\josht\Desktop\royale_sample_prjs\royale\royalelibs\samplelib\src\main\royale\com\example\MyMXMLExtendedComp2.mxml Internal error in file scope builder subsystem, when generating code for: c:\Users\josht\Desktop\royale_sample_prjs\royale\royalelibs\samplelib\src\main\royale\com\example\MyMXMLExtendedComp2.mxml: java.lang.NullPointerException
	        at org.apache.royale.compiler.internal.definitions.DefinitionBase.toStorageName(DefinitionBase.java:282)
	        at org.apache.royale.compiler.internal.definitions.DefinitionBase.<init>(DefinitionBase.java:128)
	        at org.apache.royale.compiler.internal.definitions.ScopedDefinitionBase.<init>(ScopedDefinitionBase.java:34)
	        at org.apache.royale.compiler.internal.definitions.MemberedDefinition.<init>(MemberedDefinition.java:37)
	        at org.apache.royale.compiler.internal.definitions.TypeDefinitionBase.<init>(TypeDefinitionBase.java:59)
	        at org.apache.royale.compiler.internal.definitions.ClassDefinitionBase.<init>(ClassDefinitionBase.java:60)
	        at org.apache.royale.compiler.internal.definitions.ClassDefinition.<init>(ClassDefinition.java:207)
	        at org.apache.royale.compiler.internal.definitions.ClassDefinition.<init>(ClassDefinition.java:188)
	        at org.apache.royale.compiler.internal.parsing.mxml.MXMLScopeBuilder.processRootTag(MXMLScopeBuilder.java:199)
	        at org.apache.royale.compiler.internal.parsing.mxml.MXMLScopeBuilder.build(MXMLScopeBuilder.java:169)
	        at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleFileScopeRequest(MXMLCompilationUnit.java:171)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase.processFileScopeRequest(CompilationUnitBase.java:863)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$200(CompilationUnitBase.java:108)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:287)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase$3$1.call(CompilationUnitBase.java:283)
	        at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
	        at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
	        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	        at java.lang.Thread.run(Thread.java:748)



	c:\Users\josht\Desktop\royale_sample_prjs\royale\royalelibs\samplelib\src\main\royale\com\example\MyMXMLExtendedComp2.mxml Internal error in outgoing dependency subsystem, when generating code for: c:\Users\josht\Desktop\royale_sample_prjs\royale\royalelibs\samplelib\src\main\royale\com\example\MyMXMLExtendedComp2.mxml: java.lang.NullPointerException
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase.startParsingImports(CompilationUnitBase.java:909)
	        at org.apache.royale.compiler.internal.units.MXMLCompilationUnit.handleOutgoingDependenciesRequest(MXMLCompilationUnit.java:240)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase.processOutgoingDependenciesRequest(CompilationUnitBase.java:891)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase.access$500(CompilationUnitBase.java:108)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase$6$1.call(CompilationUnitBase.java:387)
	        at org.apache.royale.compiler.internal.units.CompilationUnitBase$6$1.call(CompilationUnitBase.java:383)
	        at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228)
	        at org.apache.royale.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222)
	        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	        at java.lang.Thread.run(Thread.java:748)



	2.5225209 seconds
	The terminal process terminated with exit code: 3

**Comment by joshtynjala** [comment]
@carlosrovira I have determined that this is a bug in the Royale compiler.

As a workaround, you should specify the `source-path` compiler option in *asconfig.json*:

```
"source-path": [
    "src/main/royale"
]
```

The reason that you have been able to build successfully with Maven is probably because of this line in *pom.xml*:

```
<sourceDirectory>src/main/royale</sourceDirectory>
```

I suspect that this line sets the `source-path` compiler option behind the scenes.

**Comment by joshtynjala** [comment]
@carlosrovira In the process of my investigation, I found a separate (but somewhat related) issue in the VSCode extension. The extension was not properly parsing the `include-namespaces` compiler option in library projects. This has been fixed in commit f05f15128507a9e1378756f148d076e1a6db4e89 and will be included in the next update.

**Comment by carlosrovira** [comment]
Hi Josh, many thanks for this. With the workaround I was able to apply to all my royale libraries and know I have 0 errors :). That was getting a real problem for us :)

About the issue in VSCode, I was noticing something strange with include-namespaces, can't say exactly what was, but is clear that something was not working properly...maybe was some kind of intermittent problem sometimes showing and sometimes not.

With this VSCode and extensions seems far more reliable. Congratulations! :)

**Comment by joshtynjala** [comment]
I'm going to close this issue, but I'll be happy to open it again, if you're still encountering it.

**Comment by carlosrovira** [comment]
Hi Josh,

it's ok for me too. I still have some issues in my multi library project. I tried to fix them many weeks ago and still have some red errors, I can try to go over again to see if is something on my side. Right now I can say. In the other hand, I can share the my source code with you with no problem If you want to have a huge code base to test this kind of things. Maybe you see something I'm missing. Thanks!
